### ISSUE TITLE
Bug/design flaw in simpletable.rb

### ISSUE THREAD

**Issue by dkellett** [metaskills/pdf-writer#1]
```
          lines.each do |line|
            pdf.send(:preprocess_text, line)
```

Assuming that the purpose of running text through the prepocessor is to have the text be altered by the prepocessing method, the above line of code throws the return away... whereas in the writer.rb text() method the following is done:

  def text(text, options = {})
      # Apply the filtering which will make underlining (and other items)
      # function.
    text = preprocess_text(text)

since the preprocess_text method in writer is the following:

 def preprocess_text(text)
    text
  end

I would assume that the purpose for the method is to allow for overriding.  As such the current design will not support that....

**Comment by metaskills** [comment]
I forked this project for Ruby 1.9 compatibility thinking it was needed for my day job. It turns out we have migrated first to PDFKit before our move to 1.9 and hence will not need this fork. Though I will not delete the fork as others have found it useful too, it is not a repo that should/will take poor design decisions from the orig author. Who ever that is :)
